server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_santander
    username: postgres
    password: Vl@.div-71k75
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto API Cotação de Ações - Santander Dev Week / DIO
  version: 1.0
  urlTermsOfService: http://swagger.io/terms/
  licenseName: Apache 2.0
  urlLicense: http://springdoc.org