USE [master]
GO

/****** Object:  Database [Ecomerce]    Script Date: 05/04/2021 17:16:28 ******/
DROP DATABASE [Ecomerce]
GO

/****** Object:  Database [Ecomerce]    Script Date: 05/04/2021 17:16:28 ******/
CREATE DATABASE [Ecomerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ecomerce', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DEVOPS2019\MSSQL\DATA\Ecomerce.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ecomerce_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DEVOPS2019\MSSQL\DATA\Ecomerce_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ecomerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ecomerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ecomerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ecomerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ecomerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ecomerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ecomerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ecomerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ecomerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ecomerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ecomerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ecomerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ecomerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ecomerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ecomerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ecomerce] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ecomerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ecomerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ecomerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ecomerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ecomerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ecomerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ecomerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ecomerce] SET RECOVERY FULL 
GO

ALTER DATABASE [Ecomerce] SET  MULTI_USER 
GO

ALTER DATABASE [Ecomerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ecomerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ecomerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ecomerce] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Ecomerce] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ecomerce] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Ecomerce] SET  READ_WRITE 
GO

